type: oauth2
flow: application
tokenUrl: 'https://authserver.example/token'
scopes:
  accounts: Ability to read Accounts information
description: TPP client credential authorisation flow with the ASPSP
